---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{- include "shortlist-rm-ingester.labels" . | nindent 4 }}
  name: {{ include "shortlist-rm-ingester.fullname" . }}
  namespace: shortlist
spec:
  schedule: "{{ .Values.cron.schedule }}"
  jobTemplate:
    metadata:
      labels:
        {{- include "shortlist-rm-ingester.labels" . | nindent 8 }}
      name: {{ include "shortlist-rm-ingester.fullname" . }}
      namespace: shortlist
    spec:
      completions: 1
      backoffLimit: 1
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "shortlist-rm-ingester.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          containers:
          - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}" 
            args:
            - "--redis-host"
            - "{{ .Values.redis.hostname }}"
            - "--redis-pass"
            - "{{ .Values.redis.password }}"
            - "ingest"
            - "{{ .Values.ingester.resultsUrl }}"
            - "{{ .Values.ingester.runnerUrl }}"
            name: ingester
            resources: {}
            env:
            - name: BASE_LISTING_URL
            - value: {{ .Values.ingester.baseListingUrl }}
          restartPolicy: Never
