apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "shortlist-runner.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
  name: {{ include "shortlist-runner.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "shortlist-runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "shortlist-runner.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "shortlist-runner.fullname" . }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ .Chart.Name }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: NOTIFIER_URL
          value: {{ .Values.runner.notifierUrl }}
        - name: ASSESSOR_CACHE_PV_NAME
          value: {{ include "shortlist-runner.fullname" . }}-assessor-cache 
        - name: ASSESSOR_NODE_SELECTOR_KEY
          value: {{ .Values.assessor.nodeSelectorKey }}
        - name: ASSESSOR_NODE_SELECTOR_VALUE
          value: {{ .Values.assessor.nodeSelectorValue }}
        - name: ASSESSOR_IMAGE
          value: {{ .Values.assessor.image }}
        - name: ASSESSOR_CONFIG_PATH
          value: /etc/shortlist-assessor/config.json
        volumeMounts:
        - name: assessor-config
          mountPath: /etc/shortlist-assessor
      volumes:
      - name: assessor-config
        configMap:
          name: {{ include "shortlist-runner.fullname" . }}-assessor-config 
