apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "shortlist-runner.fullname" . }}-assessor-cache 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: standard-rwo
