apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "shortlist-runner.fullname" . }}-assessor-cache 
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: {{ .Values.assessor.cachePersistentDiskName }}

