---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shortlist-runner.fullname" . }}-assessor
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.assessor.googleServiceAccountEmail }} 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shortlist-runner.fullname" . }}
  namespace: {{ .Values.namespace }}
apiVersion: rbac.authorization.k8s.io/v1
