apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "shortlist-rm-email-notifier.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
  name: {{ include "shortlist-rm-email-notifier.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "shortlist-rm-email-notifier.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "shortlist-rm-email-notifier.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "shortlist-rm-email-notifier.fullname" . }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ .Chart.Name }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: AWS_SES_IDENTITY_ARN
          value: {{ .Values.aws.sesIdentityArn }}
        - name: AWS_REGION
          value: {{ .Values.region }}
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: '/var/run/secrets/tokens/{{ include "shortlist-rm-email-notifier.fullname" . }}-token'
        - name: AWS_ROLE_ARN
          value: {{ .Values.aws.roleArn }}
        volumeMounts:
        - mountPath: /var/run/secrets/tokens
          name: '{{ include "shortlist-rm-email-notifier.fullname" . }}-token'
      volumes:
      - name: '{{ include "shortlist-rm-email-notifier.fullname" . }}-token'
        projected:
          sources:
          - serviceAccountToken:
            path: '{{ include "shortlist-rm-email-notifier.fullname" . }}-token'
            expirationSeconds: 86400
            audience: sts.amazonaws.com
